pipelines:
  pipeline-lambda:
    display_order: 1
    environment_variables:
      DEBUG: ''
      IGNORE_DRIFT: false
    group: dwh-report
    materials:
      git_repo_1:
        branch: master
        destination: node-express-dashboard
        git: https://github.com/tuannguyenm/node-express-dashboard.git
        whitelist:
          - node-express-dashboard/json/settings.json
      git_repo_2:
        branch: master
        destination: node-express-image-processing-server
        git: https://github.com/tuannguyenm/node-express-image-processing-server.git
        whitelist:
          - node-express-image-processing-server/test/mocha-config.js
    stages:
      - apply:
          jobs:
            apply:
              tasks:
                - exec:
                    working_directory: node-express-dashboard/json
                    command: touch
                    arguments:
                      - settings.json
      - deploy:
          jobs:
            deploy:
              tasks:
                - exec:
                    working_directory: node-express-image-processing-server/test
                    command: touch
                    arguments:
                      - mocha-config.js   
